float32[]       path            # the trajectory of the shape
uint32          shape_id         # the ID of the instance of the shape
string          shape_type       # the type of the shape
uint32          shape_type_code  # the code of the type of the shape
uint8[]         params_to_vary    # which parameters are varying in the shape model
float32[]       param_values     # the parameter values used to make this shape